name = "browser-bot"
main = "src/index.ts"
compatibility_date = "2025-01-15"
compatibility_flags = ["nodejs_compat"]

# This creates the Browser Rendering binding the code will use.
[browser]
binding = "BROWSER"
