name: crawl-and-rank
on:
  workflow_dispatch: {}

permissions:
  contents: write

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: python scripts/crawl.py
      - run: python scripts/rank.py
      - name: Commit dashboard data
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/scores.jsonl docs/data/scores.json
          git commit -m "Update scores [skip ci]" || echo "No changes"
          git push
