name: draft-covers
on:
  workflow_dispatch:
    inputs:
      top:
        description: "Number of top roles to draft"
        required: false
        default: "5"

permissions:
  contents: write

env:
  PYTHONPATH: ${{ github.workspace }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - run: python scripts/draft_email.py --top ${{ github.event.inputs.top }}
      - name: Commit cover drafts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/outbox/
          git commit -m "Update cover drafts [skip ci]" || echo "No changes"
          git push
