name: tailor-user

on:
  workflow_dispatch:
    inputs:
      user_id:
        description: Supabase user id
        required: true
      request_id:
        description: job_requests id
        required: true

permissions:
  contents: read

env:
  PYTHONPATH: ${{ github.workspace }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt python-docx requests pyyaml beautifulsoup4

      # Mark request as running early (better UX)
      - name: Mark job_requests as running
        run: |
          set -euo pipefail
          curl -sS -X PATCH \
            "${SUPABASE_URL%/}/rest/v1/job_requests?id=eq.${{ github.event.inputs.request_id }}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            --data '{"status":"running"}'

      - name: Fetch user's latest resume
        run: python scripts/fetch_user_assets.py --user "${{ github.event.inputs.user_id }}"

      - name: Parse resume -> upsert profile
        run: python scripts/parse_resume.py --user "${{ github.event.inputs.user_id }}"

      - name: Crawl targets
        run: python scripts/crawl.py

      - name: Rank jobs
        run: python scripts/rank.py --user "${{ github.event.inputs.user_id }}"

      # ---------- Export & Upload Profile JSON for the Profile page ----------
      - name: Export profile JSON (service role)
        run: |
          set -euo pipefail
          mkdir -p docs/data
          curl -sS \
            "${SUPABASE_URL%/}/rest/v1/profiles?id=eq.${{ github.event.inputs.user_id }}&select=*" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -o docs/data/profile.json
          # Normalize: the REST response is an array; keep the first object
          python - << 'PY'
import json, sys
p = "docs/data/profile.json"
arr = json.load(open(p)) if open(p).read().strip() else []
obj = (arr[0] if isinstance(arr, list) and arr else {})
json.dump(obj, open(p, "w"), indent=2)
print(f"Wrote {p} ({'empty' if not obj else 'ok'})")
PY

      - name: Upload shortlist to outputs/<uid>/scores.json
        run: |
          set -euo pipefail
          OUT_JSON="docs/data/scores.json"
          if [ ! -f "$OUT_JSON" ]; then
            echo "scores.json not found at $OUT_JSON"; exit 1
          fi
          curl -sS -X POST \
            "${SUPABASE_URL%/}/storage/v1/object/outputs/${{ github.event.inputs.user_id }}/scores.json" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            -H "x-upsert: true" \
            --data-binary @"$OUT_JSON"

      - name: Upload profile to outputs/<uid>/profile.json
        run: |
          set -euo pipefail
          PROF_JSON="docs/data/profile.json"
          if [ ! -f "$PROF_JSON" ]; then
            echo "profile.json not found at $PROF_JSON"; exit 1
          fi
          curl -sS -X POST \
            "${SUPABASE_URL%/}/storage/v1/object/outputs/${{ github.event.inputs.user_id }}/profile.json" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            -H "x-upsert: true" \
            --data-binary @"$PROF_JSON"

      # ---------- Debug artifacts so you can inspect each run ----------
      - name: Upload run artifacts (jobs.jsonl, scores.json, profile.json)
        uses: actions/upload-artifact@v4
        with:
          name: run-artifacts-${{ github.event.inputs.user_id }}
          path: |
            data/jobs.jsonl
            docs/data/scores.json
            docs/data/profile.json
          if-no-files-found: warn
          retention-days: 7

      - name: Mark job_requests as done
        if: ${{ success() }}
        run: |
          set -euo pipefail
          curl -sS -X PATCH \
            "${SUPABASE_URL%/}/rest/v1/job_requests?id=eq.${{ github.event.inputs.request_id }}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            --data '{"status":"done"}'

      - name: Mark job_requests as error (with message)
        if: ${{ failure() }}
        run: |
          set -euo pipefail
          MSG=$(jq -n --arg m "worker failed; check GH logs" '{"status":"error","message":$m}')
          curl -sS -X PATCH \
            "${SUPABASE_URL%/}/rest/v1/job_requests?id=eq.${{ github.event.inputs.request_id }}" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "apikey: ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=minimal" \
            --data "$MSG"
