name: tailor-user
on:
  workflow_dispatch:
    inputs:
      user_id: { description: "Supabase user id", required: true }
      request_id: { description: "job_requests id", required: true }

permissions:
  contents: write

env:
  PYTHONPATH: ${{ github.workspace }}
  SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
  SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Install deps
        run: pip install -r requirements.txt python-docx requests

      - name: Fetch user's resume from Supabase
        run: python scripts/fetch_user_assets.py --user "${{ github.event.inputs.user_id }}"

      - name: Parse resume and upsert profile (autofill)
        run: python scripts/parse_resume.py --user "${{ github.event.inputs.user_id }}"

      - name: Draft covers & resumes (top=5)
        run: python scripts/draft_email.py --top 5

      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/outbox/ -A || true
          git add docs/resumes/ -A || true
          git add docs/changes/ -A || true
          git add docs/data/scores.json || true
          git commit -m "Tailor run ${{ github.event.inputs.request_id }} [skip ci]" || echo "No changes"
          git push || true
